# Terraform Block

terraform 
{
  required_version = ">= 0.15"
  required_providers 
{
    azurerm = 
{
      source = "hashicorp/azurerm"
      version = ">= 2.0" 
    }
    random =
{
      source = "hashicorp/random"
      version = ">= 3.0"
    }
  }
}

# Provider Block

provider "azurerm" 
{
 features {}          
}

# Random String Resource

resource "random_string" "myrandom"
{
  length = 6
  upper = false 
  special = false
  number = false   
}

----------------------------------------------------------------------------------------------------------------------------------------

# Explanation: - 

### Terraform Block

- The Terraform block is a global configuration block that controls Terraform's core behavior, such as specifying acceptable Terraform CLI versions and declaring required providers.

- It does not define infrastructure resources, but rather sets the foundation for your infrastructure code.

terraform 
{
  required_version = ">= 0.15"
  required_providers
{
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">= 2.0" 
    }
    random = 
{
      source = "hashicorp/random"
      version = ">= 3.0"
    }
  }
}


- required_version: Ensures that anyone executing this code uses at least Terraform version 0.15.0. 
     - If a user tries to run it with an older version, Terraform will reject the operation.

- required_providers: Declares which plugins (providers) are needed for your infrastructure.

In this case, it specifies:

  - azurerm: The Microsoft Azure provider, sourced from hashicorp/azurerm on the official Terraform registry, with a minimum required version of 2.0.0.
  
   - random: The HashiCorp Random provider, sourced from hashicorp/random, with a minimum version of 3.0.0.

- source: Indicates where Terraform should download the provider from (the official HashiCorp registry). A unique address can be assigned to each provider.

- version: Specifies the minimum provider version for compatibility.

### Provider Block

- The provider block configures how a declared provider should operate. 

- It is where you specify authentication, regions, and other provider-specific settings.

provider "azurerm" 
{
  features {}          
}

- provider "azurerm": Configures the Azure provider. 
  The features {} block is required for the Azure provider to enable or disable certain behaviors; here, it is an empty block, so the provider uses default features.

- No explicit configuration: There are no authentication details (client ID, tenant ID, etc.) 
  In this block, which typically means the provider will use default Azure authentication methods (such as via the Azure CLI or environment variables).

### Random String Resource

The resource block actually creates a real-world resource. Here, it is not an Azure resource, but a local, non-cloud resource generated by the HashiCorp Random provider:

resource "random_string" "myrandom" 
{
  length = 6
  upper = false 
  special = false
  number = false   
}

- resource "random_string" "myrandom": Creates a resource named myrandom of type random_string.
- length = 6: The string will be 6 characters long.
- upper = false: The string will not include uppercase ASCII letters.
- special = false: The string will not include special characters.
- number = false: The string will not include digits.
- Result: This resource generates a random string consisting only of lowercase ASCII letters, which could be useful for creating unique identifiers, passwords, or names within your Terraform configuration.

### Summary Table

|   Block/Resource          |            Purpose                     |      Example Syntax       |                    Key Points                                        |
|---------------------------|----------------------------------------|---------------------------|----------------------------------------------------------------------|
|  terraform                |  Global Terraform configuration        |  terraform {}             |  Defines required versions and providers; does not manage infra      |
|  required_providers       |  Declares plugin/provider dependencies |  required_providers {}    |  Sets provider names, sources, and version constraints               |
|  provider                 |  Configures a provider instance        |  provider "azurerm" {}    |  Sets authentication, features, or region; may be empty for defaults |
|  resource (random_string) |  Creates a random string resource      |  resource "random_string" |  Generates random strings for IDs/passwords in configs               |

